services:

- type: web
  name: n8n
  env: node
  plan: free
  region: oregon
  
  buildCommand: npm install
  startCommand: npx n8n
  
  envVars:
  
  - key: NODE_VERSION
    value: 20
  
  - key: NODE_OPTIONS
    value: --max-old-space-size=256
  
  - key: DB_TYPE
    value: sqlite
  
  - key: N8N_SECURE_COOKIE
    value: false
  
  - key: N8N_BASIC_AUTH_ACTIVE
    value: true
  
  - key: N8N_BASIC_AUTH_USER
    value: admin
  
  - key: N8N_BASIC_AUTH_PASSWORD
    value: admin123
  
  - key: GENERIC_TIMEZONE
    value: Asia/Karachi
